/**
 * Indeks dokumentacji + grupy znaczeniowe.
 * Szukanie nie opiera się tylko o dokładne słowo — fraza jest
 * rozwijana o synonimy i pojęcia z tej samej dziedziny (blaty, FC3D).
 */
export const SEARCH_DOCS = [
  {
    id: 'intro',
    title: 'Wprowadzenie',
    href: '/',
    category: 'Start',
    summary: 'FastCube3D — konfigurator blatów.',
    headings: ['Jak edytować dokumentację'],
    topics: [
      'wprowadzenie',
      'metodologia',
      'wdrozenie',
      'konfigurator',
      'blat',
      'fastcube',
      'fc3d',
      'start',
    ],
    text: 'FastCube3D konfigurator blatów metodologia wdrażania wizualizacja 3D',
  },
  {
    id: 'procedura-konfiguracji',
    title: 'Procedura konfiguracji FC3D',
    href: '/procedura-konfiguracji-fc3d',
    category: 'Start',
    summary: 'Krok po kroku: katalog fc3d, tabele Objects, Params Custom20, użytkownicy API i OAuth.',
    headings: [
      'Procedura konfiguracji FC3D',
      'Procedura konfiguracji API dla FC',
    ],
    topics: [
      'procedura',
      'konfiguracja',
      'pdf',
      'instrukcja',
      'wdrozenie',
      'fc3d',
      'fastcube',
      'api',
      'oauth',
      'custom20',
      'params',
      'fc3d_api',
    ],
    text: 'Procedura konfiguracji FastCube3D katalog fc3d init.php tabele Objects Params Custom20 FastCube3DUrl użytkownicy FC3D_API OAuth FC_API creator3d.',
  },
  {
    id: 'konfiguracja-bazy',
    title: 'Konfiguracja bazy zasobów',
    href: '/konfiguracja-bazy-zasobow',
    category: 'Start',
    summary: 'Źródło danych: FastCut, Order Manager i MySQL (tabela Materials).',
    headings: [],
    topics: [
      'baza',
      'mysql',
      'fastcut',
      'order manager',
      'materials',
      'kartoteka',
      'zasob',
      'dane',
      'zrodlo',
    ],
    text: 'Konfigurator FastCube3D działa w oparciu o bazę danych MySQL systemu FastCut oraz Order Manager. Tabela Materials. Podstawowe dane zasobów.',
  },
  {
    id: 'parametry-podstawowe',
    title: 'Parametry podstawowe',
    href: '/parametry-zasobu/parametry-podstawowe',
    category: 'Parametry zasobu',
    summary: 'Pola kartoteki blatu: symbol, opis, grupa, wymiary, typ zasobu.',
    headings: [
      'Konfiguracja bazy zasobów na potrzeby konfiguratora',
      'Opis zasobu oraz podstawowe parametry',
    ],
    topics: [
      'symbol',
      'opis',
      'grupa',
      'wymiar',
      'dlugosc',
      'szerokosc',
      'grubosc',
      'kartoteka',
      'mattype',
      'jednostka',
      'producent',
    ],
    text: 'Symbol SymbolProducer Description DescriptionAlias Groups MatType Unit Length Width Thicknes. Pola kartoteki zasobów do list wyboru konfiguratora.',
  },
  {
    id: 'oklejanie',
    title: 'Oklejanie niestandardowe',
    href: '/parametry-zasobu/oklejanie-niestandardowe',
    category: 'Parametry zasobu',
    summary: 'Zaokrąglenie krawędzi, docięcie fabryczne i kontrola wymiarów.',
    headings: [],
    topics: [
      'oklejanie',
      'okleina',
      'obrzeze',
      'krawedz',
      'zaokraglenie',
      'dociecie',
      'edging',
      'edge',
      'kontrola wymiarow',
    ],
    text: 'EdgeRoundLeft EdgeRoundTop EdgesType BLOCK EDGING EdgeRoundTrim SizeControlType CONTROL_SIZE. Fabrycznie wykończona krawędź, docięcie zaokrąglenia, oklejanie.',
  },
  {
    id: 'kolory-plaszczyzn',
    title: 'Kolory płaszczyzn',
    href: '/parametry-zasobu/kolory-plaszczyzn',
    category: 'Parametry zasobu',
    summary: 'Kolor, tekstura i skalowanie powierzchni blatu (góra, dół, krawędzie, wnętrze).',
    headings: [],
    topics: [
      'kolor',
      'plaszczyzna',
      'powierzchnia',
      'tekstura',
      'texture',
      'wyglad',
      'dekór',
      'dekor',
      'skalowanie',
      'hex',
      'color',
      'wierzch',
      'spod',
    ],
    text: 'Color Color1 Color2 Color3 Color4 Color5 Color6 ColorInSide TextureScaleV TextureScaleU TextureFileName TextureFileNameInSide. Kolor wszystkich płaszczyzn, góra, dół, krawędzie, wnętrze, nazwa pliku tekstury, skalowanie UxV.',
  },
  {
    id: 'zmienne',
    title: 'Zmienne standardowe oraz indywidualne',
    href: '/sety/zmienne-standardowe-i-indywidualne',
    category: 'Sety i powiązania',
    summary: 'Sety zmiennych StandardVariables i DefinedVariables dla blatów.',
    headings: ['Zmienne standardowe oraz indywidualne — Sety'],
    topics: [
      'zmienne',
      'set',
      'sety',
      'standardvariables',
      'definedvariables',
      'zaciecie',
      'optymalizacja',
      'nadmiar',
    ],
    text: '_wt_SysMatJoinType _wt_SysDefOptInc DefinedVariables StandardVariables WT_JOIN_TYPE WT_EDGES_FRONT_TYPE. Sety zmiennych, zacięcie, długość do rozkroju.',
  },
  {
    id: 'zlacz',
    title: 'Powiązane złącza z blatem',
    href: '/sety/powiazane-zlacz',
    category: 'Sety i powiązania',
    summary: 'WORKTOP_JOIN, indeksy QUICK L=64/100/150 i złącze domyślne.',
    headings: ['Definicja opcji rozszerzonych dla złącza'],
    topics: [
      'zlacz',
      'zlacze',
      'laczenie',
      'polaczenie',
      'quick',
      'worktop_join',
      'join',
      'domyslne',
      'indeks',
    ],
    text: 'Id operacji WORKTOP_JOIN Opcje 1 WT_JOIN_TYPE QUICK L=64 L=100 L=150 Opcje 2 złącze domyślne. Powiązane złącza z blatem.',
  },
  {
    id: 'okleiny-zlacz',
    title: 'Powiązania oklein oraz złączy',
    href: '/sety/powiazania-oklein-zlaczy',
    category: 'Sety i powiązania',
    summary: 'Powiązanie obrzeży i złączy QUICK z kartoteką blatu.',
    headings: [],
    topics: [
      'okleina',
      'obrzeze',
      'zlacz',
      'powiazanie',
      'quick',
      'wybor zlacza',
    ],
    text: 'Powiązania oklein oraz złączy. Obrzeże, złącza QUICK, wybór typu złącza w konfiguratorze.',
  },
  {
    id: 'otwory',
    title: 'Powiązania usług z otworami',
    href: '/sety/powiazania-uslug-otworow',
    category: 'Sety i powiązania',
    summary: 'Zmienne OPER_* — wycena otworów koło/prostokąt i nutów.',
    headings: [],
    topics: [
      'otwor',
      'nawiart',
      'dziura',
      'wyciecie',
      'frezowanie',
      'nut',
      'usluga',
      'oper',
      'srednica',
      'obwod',
    ],
    text: 'OPER_CIRC_PCS_61 OPER_DIA_PCS_61 OPER_CIRC_PCS_71 OTWOR_PROST_PCS OTWOR_KOLO_PCS. Usługi otworów koło prostokąt nawiert nut. Id operacji Opcje 2 zakres.',
  },
  {
    id: 'migracja',
    title: 'Migracja V4 → V6',
    href: '/migracja/migracja-v4-v6',
    category: 'Migracja',
    summary: 'Kroki po migracji: zmienne, ścieżki, usługi, złącza, tekstury, SQL.',
    headings: [
      '1. Ustawić',
      '2. Zmodyfikować ścieżkę',
      '3. Zdefiniować usługi',
      '4. Powiązać kartoteki rozliczeniowe',
      '5. Zakres obwodu otworów prostokątnych',
      '6. Zakres średnic otworów okrągłych',
      '7. Konfiguracja złączy',
      '8. Wgrać tekstury do plugins',
      '9. Powiązanie usług i złączy SQL',
      '10. Ukrycie wymiarów',
    ],
    topics: [
      'migracja',
      'v4',
      'v6',
      'sciezka',
      'plugin',
      'sql',
      'showoperation',
      'tekstura',
      'ukrycie wymiarow',
    ],
    text: 'Part.ShowOperation61 FastCube3DUrl OPER_PCS_61 MAT_SUB_TYPE WORKTOP_JOIN tekstury plugins _SysHideDimensionsJoinLine SELECT tw__Towar. Migracja V4 V6.',
  },
  {
    id: 'uzupelnienia',
    title: 'Parametry do uzupełnienia',
    href: '/parametry-do-uzupelnienia',
    category: 'Start',
    summary:
      'SQL UPDATE dla blatów: kolor, tekstura, zaokrąglenia, poziom zagnieżdzenia, brzegowanie, oklejanie, optymalizacja.',
    headings: [
      'HPL',
      'BLATY 38 MM',
      'Parametry blatów 38 mm',
      'Zaokrąglenia dla blatów',
      'Optymalizacja wg materiału',
      'Kolor spodu',
      'Dostępny w FC3D',
      'Brzegowanie wg materiału',
      'Poziom zagnieżdzenia',
      'Optymalizacja — pasy po szerokości',
      'Ilość w sztaplu',
      'Optymalizacja połówek',
      'Pasy pionowe dla połówek',
      'Blokowanie pogrubiania',
      'Docięcie zaokrąglonej krawędzi',
      'Tylko powiązane okleiny',
      'Wyłącz / włącz domyślne oklejanie',
      'Wyłącz / włącz blokowanie oklejania',
    ],
    topics: [
      'sql',
      'update',
      'placeholder',
      'kolor',
      'kolor spodu',
      'tekstura',
      'wciecie',
      'blokowanie krawedzi',
      'hpl',
      'nazwaobrazka',
      'zagniezdzenie',
      'poziom zagniezdzenia',
      'optimizecalctype',
      'zaokraglenia',
      'zaokraglenia dla blatow',
      'edgeroundtop',
      'edgeroundbottom',
      'edgeroundtrim',
      'docięcie zaokraglonej krawedzi',
      'dociecie zaokraglonej krawedzi',
      'brzegowanie',
      'brzegowanie wg materialu',
      'trim',
      'trim1',
      'trim2',
      'trim3',
      'trim4',
      'optymalizacja',
      'optymalizacja wg materialu',
      'optimizeusecustomoptions',
      'pasy',
      'pasy po szerokosci',
      'stripspreffered',
      'stripsdirection',
      'pasy pionowe',
      'pasy poziome',
      'polowki',
      'optymalizacja polowek',
      'stripsboardlasthalf',
      'sztapel',
      'ilosc w sztaplu',
      'optimizemaxqntinstack',
      'oklejanie',
      'domyslne oklejanie',
      'blokowanie oklejania',
      'edgeblock',
      'edgeblockleft',
      'edgeblocktop',
      'edgeblockright',
      'edgeblockbottom',
      'edgedefault',
      'edgedefaultleft',
      'edgedefaulttop',
      'edgedefaultright',
      'edgedefaultbottom',
      'powiazane okleiny',
      'edgeallowonlyassociated',
      'flagshowin3d',
      'dostepny w fc3d',
      'color2',
      'boldingblock',
      'blokowanie pogrubiania',
      'pogrubianie',
      'mattype',
      'thicknes',
      'width',
      'blaty 38',
      '38 mm',
      'materials',
    ],
    text: `
Ustawienie kolor textura zmienna blokowanie krawedzi HPL BLATY 38 MM.
UPDATE Materials Color3 Color4 Color5 Color6 ColorInSide TextureFileNameInSide StandardVariables nazwaObrazka wartosc wciecia.
Zaokraglenia dla blatow EdgeRoundTop EdgeRoundBottom Width 600 900 1200.
Optymalizacja wg materialu OptimizeUseCustomOptions.
Kolor spodu Color2 #D2B48C.
Dostepny w FC3D FlagShowIn3D.
Brzegowanie wg materialu Trim1 Trim2 Trim3 Trim4.
Poziom zagniezdzenia OptimizeCalcType 0 2D 3 pasy proste 5 1D.
Optymalizacja pasy po szerokosci StripsPreffered 200.
Ilosc w sztaplu OptimizeMaxQntInStack.
Optymalizacja polowek StripsBoardLastHalf.
Pasy pionowe dla polowek StripsDirection 1 poziome 0 auto 2.
Blokowanie pogrubiania BoldingBlock.
Dociecie zaokraglonej krawedzi EdgeRoundTrim.
Tylko powiazane okleiny EdgeAllowOnlyAssociated.
Wylacz wlacz domyslne oklejanie EdgeDefaultLeft EdgeDefaultTop EdgeDefaultRight EdgeDefaultBottom.
Wylacz wlacz blokowanie oklejania EdgeBlockLeft EdgeBlockTop EdgeBlockRight EdgeBlockBottom.
MatType 4 4;200 Thicknes 38.
`.replace(/\s+/g, ' ').trim(),
  },
  {
    id: 'zmiany',
    title: 'Zmiany',
    href: '/zmiany',
    category: 'Start',
    summary: 'Historia zmian dokumentacji (v372).',
    headings: [],
    topics: ['changelog', 'wersja', 'v372', 'historia'],
    text: 'Zmiany v372',
  },
  {
    id: 'jak-edytowac',
    title: 'Jak edytować dokumentację',
    href: '/jak-edytowac-dokumentacje',
    category: 'Start',
    summary: 'Współtworzenie docs: clone, npm start, commit, pull request i publikacja.',
    headings: [
      'Pobierz projekt',
      'Uruchom lokalnie',
      'Wprowadź zmiany',
      'Sprawdź zmianę',
      'Zapisz w Gicie',
      'Wyślij na GitHub',
      'Jak opublikować zmiany na stronie',
      'Najważniejsze komendy',
    ],
    topics: [
      'edycja',
      'dokumentacja',
      'github',
      'git',
      'pull request',
      'publikacja',
      'roadmap',
      'wspoltworzenie',
      'npm',
    ],
    text: 'Jak edytować dokumentację FC3D git clone npm start docs md commit push pull request Actions GitHub Pages.',
  },
];

/**
 * Grupy pojęć: wpisanie dowolnego członu rozwija zapytanie o resztę grupy.
 * Dzięki temu „ustalanie powierzchni” trafia też w tekstury i kolory płaszczyzn.
 */
export const SYNONYM_GROUPS = [
  [
    'powierzchnia',
    'powierzchnie',
    'plaszczyzna',
    'plaszczyzny',
    'wierzch',
    'spod',
    'wyglad',
    'dekór',
    'dekor',
    'face',
    'surface',
    'kolor',
    'kolory',
    'barwa',
    'tekstura',
    'tekstury',
    'texture',
    'textura',
    'okleina wizualna',
  ],
  [
    'ustalanie',
    'ustawianie',
    'ustawienie',
    'konfiguracja',
    'konfigurowanie',
    'definicja',
    'definiowanie',
    'parametryzacja',
    'nadawanie',
    'przypisanie',
    'uzupelnianie',
  ],
  [
    'zlacze',
    'zlacz',
    'zlaczka',
    'laczenie',
    'polaczenie',
    'polacz',
    'join',
    'quick',
    'worktop_join',
    'spinka',
  ],
  [
    'otwor',
    'otwory',
    'nawiart',
    'nawiert',
    'dziura',
    'wyciecie',
    'frezowanie',
    'wycięcie',
    'nut',
    'nuta',
    'hole',
  ],
  [
    'okleina',
    'oklejanie',
    'obrzeze',
    'obrzeże',
    'krawedz',
    'krawedzie',
    'edging',
    'edge',
    'kant',
  ],
  [
    'baza',
    'mysql',
    'kartoteka',
    'zasob',
    'material',
    'materials',
    'dane',
    'fastcut',
    'om',
  ],
  [
    'wymiar',
    'wymiary',
    'dlugosc',
    'szerokosc',
    'grubosc',
    'formatka',
    'rozmiar',
    'size',
  ],
  [
    'zagniezdzenie',
    'zagniezdzenia',
    'poziom zagniezdzenia',
    'optimizecalctype',
    'nesting',
    '2d',
    '1d',
    'pasy',
  ],
  [
    'zaokraglenie',
    'zaokraglenia',
    'edgeroundtop',
    'edgeroundbottom',
    'edgeroundtrim',
    'zaoblona',
    'zaoblenie',
  ],
  [
    'brzegowanie',
    'trim',
    'trim1',
    'trim2',
    'trim3',
    'trim4',
  ],
  [
    'sztapel',
    'stos',
    'optimizemaxqntinstack',
    'ilosc w sztaplu',
  ],
  [
    'polowki',
    'polowa',
    'stripsboardlasthalf',
    'stripsdirection',
    'stripspreffered',
  ],
  [
    'pogrubianie',
    'boldingblock',
    'pogrubienie',
  ],
  [
    'zmienna',
    'zmienne',
    'set',
    'sety',
    'parametr',
    'parametry',
  ],
  [
    'migracja',
    'wdrozenie',
    'plugin',
    'sciezka',
  ],
];

/** Gotowe frazy użytkownika → dokument (kontekst, nie tylko słowo). */
export const PHRASE_HINTS = [
  {
    patterns: [
      'ustalanie powierzchni',
      'ustawienie powierzchni',
      'ustawianie powierzchni',
      'wyglad blatu',
      'wygląd blatu',
      'powierzchnia blatu',
      'kolor blatu',
      'tekstura blatu',
    ],
    boostIds: ['kolory-plaszczyzn', 'uzupelnienia', 'parametry-podstawowe'],
  },
  {
    patterns: ['zlacze', 'łączenie blatów', 'laczenie blatow', 'quick'],
    boostIds: ['zlacz', 'okleiny-zlacz', 'migracja'],
  },
  {
    patterns: ['otwor', 'nawiert', 'dziura w blacie', 'wyciecie'],
    boostIds: ['otwory', 'migracja'],
  },
  {
    patterns: ['edytowac dokumentacje', 'jak edytować', 'pull request', 'github', 'publikacja'],
    boostIds: ['jak-edytowac', 'intro'],
  },
  {
    patterns: [
      'poziom zagniezdzenia',
      'poziom zagnieżdzenia',
      'zagniezdzenie',
      'zagnieżdzenie',
      'optimizecalctype',
      'zaokraglenia',
      'zaokraglenia blatow',
      'zaokrąglenia',
      'zaokrąglenia blatów',
      'edgeroundtop',
      'edgeroundbottom',
      'edgeroundtrim',
      'docięcie zaokraglonej',
      'dociecie zaokraglonej',
      'brzegowanie',
      'trim1',
      'trim2',
      'trim3',
      'trim4',
      'optymalizacja wg materialu',
      'optimizeusecustomoptions',
      'kolor spodu',
      'color2',
      'dostepny w fc3d',
      'flagshowin3d',
      'pasy po szerokosci',
      'stripspreffered',
      'ilosc w sztaplu',
      'sztapel',
      'optimizemaxqntinstack',
      'optymalizacja polowek',
      'polowki',
      'stripsboardlasthalf',
      'pasy pionowe',
      'pasy poziome',
      'stripsdirection',
      'blokowanie pogrubiania',
      'pogrubianie',
      'boldingblock',
      'powiazane okleiny',
      'edgeallowonlyassociated',
      'domyslne oklejanie',
      'edgedefault',
      'blokowanie oklejania',
      'edgeblock',
      'blaty 38',
      'thicknes 38',
    ],
    boostIds: ['uzupelnienia'],
  },
];
